language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
before_install:
  - npm install -g npm@latest
install:
  - npm --version
  - npm install --registry http://registry.npmjs.org
script:
  - npm test
after_script:
  - npm run coveralls